apiVersion: v1
kind: Pod
metadata:
  name: echo
  labels:
    name: echo
    app: echo
spec:
  containers:
  - name: echo
    image: hashicorp/http-echo
    args:
      - -text="hello world v2"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: echo
spec:
  selector:
    app: echo
  ports:
  - port: 5678
    targetPort: 5678
  type: LoadBalancer

